gastos/gastos/urls.py
from django.contrib import admin
from django.urls import path, include
from mainGastos.views import index,signup,account_activation_sent,activate,cuenta_activada,resumen
#from crudbuilder import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate, name='activate'),
    path('',index,name="index"),
    path('registro/',signup,name="registro"),
    path('registro/exito',cuenta_activada,name='c_activada'),
    path('control/', include('mainGastos.urls')),
    path('resumen/<int:plk>',resumen,name="resumen")
]

gastos/mainGastos/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Categorias(models.Model):
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    nombre = models.CharField(max_length=150)

    def __str__(self):
        return self.nombre

class Perfiles(models.Model):
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    nombre = models.CharField(max_length=150)
    fecha_de_creacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.nombre
    
class Gastos(models.Model):
    fk_id_categoria = models.ForeignKey(Categorias,on_delete=models.CASCADE,null = True)
    fk_id_perfil = models.ForeignKey(Perfiles,on_delete=models.CASCADE, null = True)
    descripción = models.CharField(max_length=200,null=True,blank=True)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    fecha = models.DateField()

    def __str__(self):
        if( self.descripción == None):
            return "Gasto sin descripción ("+str(self.precio)+"€)"
        return self.descripción+" ("+str(self.precio)+"€)"

gastos/templates/crud/categoria/categoria_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            {% if perms.mainGastos.delete_categorias and isOwner %}
                <h1>Borrar categoría</h1>
                <form method="post">{% csrf_token %}
                    ¿Estás seguro de eliminar "{{ object }}" ?
                    <input class='btn btn-danger' type="submit" value="Borrar" />
                </form>
            {% else %}
                <p>Lo sentimos, no dispones de permisos para eliminar este item.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

gastos/templates/crud/categoria/categoria_create_form.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-12 col-md-6">

            <h1 class="text-center">Crear categoría</h1>
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary mt-2" type="submit" value="Enviar" />
            </form>

        </div>
    </div>
</div>

{% endblock %}

gastos/templates/crud/categoria/categoria_form.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col">
            {% if perms.mainGastos.change_categorias and isOwner %}
            <h1>Editar categoría</h1>
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" value="Confirmar" />
            </form>
            {% else %}
                <p>Lo sentimos, no dispones de permisos para modificar este item.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

gastos/templates/crud/categoria/detalle_categoria.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Detalles de Categoría</h1>
            <h2>Nombre: {{object.nombre}}</h2>

        </div>
    </div>
</div>

{% endblock %}

gastos/templates/crud/categoria/listar_categoria.html
{% extends 'base.html' %}

{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% load static %}

{% block extraScripts %}
    <script src='{% static "styleCRUD.js" %}'></script>
    {% if perms.mainGastos.change_categorias %}
        <script src='{% static "customCRUD.js" %}'></script>
    {% endif %}
{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

        <!-- 
            {% if filter %}
            <form action="" method="get" class="form form-inline pt-2">
                {% bootstrap_form filter.form layout='inline' %}
                {% bootstrap_button 'filtrar' %}
            </form>
            {% endif %}
        -->
            <h1 class="text-center">Categorías</h1>

            {% if mensajeNoCategorias %}
                <p>Aún no se han añadido categorías. Puedes añadir una nueva <a href="{% url 'categoria_new' %}">aquí</a></p>
            {% else %}
                {% render_table table %}
                <a style='margin-bottom:50px;' class='btn btn-primary' href='{% url "categoria_new" %}'>Nueva</a>
            {% endif %}

        </div>
    </div>
</div>

{% endblock %}

gastos/templates/crud/categoria/telephone_form.html
{% extends 'base_template.html' %}
{% block body %}


<div class="container">
    <div class="row">
        <div class="col">

            <h1>Telephone Edit</h1>
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" value="Submit" />
            </form>

        </div>
    </div>
</div>

{% endblock %}