gastos/gastos/urls.py
from django.contrib import admin
from django.urls import path, include
from mainGastos.views import index,signup,account_activation_sent,activate,cuenta_activada,resumen
#from crudbuilder import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate, name='activate'),
    path('',index,name="index"),
    path('registro/',signup,name="registro"),
    path('registro/exito',cuenta_activada,name='c_activada'),
    path('control/', include('mainGastos.urls')),
    path('resumen/<int:plk>',resumen,name="resumen")
]

gastos/mainGastos/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Categorias(models.Model):
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    nombre = models.CharField(max_length=150)

    def __str__(self):
        return self.nombre

class Perfiles(models.Model):
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    nombre = models.CharField(max_length=150)
    fecha_de_creacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.nombre
    
class Gastos(models.Model):
    fk_id_categoria = models.ForeignKey(Categorias,on_delete=models.CASCADE,null = True)
    fk_id_perfil = models.ForeignKey(Perfiles,on_delete=models.CASCADE, null = True)
    descripción = models.CharField(max_length=200,null=True,blank=True)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    fecha = models.DateField()

    def __str__(self):
        if( self.descripción == None):
            return "Gasto sin descripción ("+str(self.precio)+"€)"
        return self.descripción+" ("+str(self.precio)+"€)"

gastos/templates/crud/gasto/detalle_gasto.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Detalles de Gasto</h1>
            <h2>Nombre: {{object.nombre}}</h2>
            <p>Categoria: {{object.fk_id_categoria}}</p>
            <p>Perfil: {{object.fk_id_perfil}}</p>
            <p>Descripcion: {{object.descripción}}</p>
            <p>Precio: {{object.precio}}</p>
            <p>Fecha: {{object.fecha}}</p>
            
        </div>
    </div>
</div>

{% endblock %}

gastos/templates/crud/gasto/gasto_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            {% if perms.mainGastos.delete_gastos and isOwner %}
                <h1>Borrar gasto</h1>
                <form method="post">{% csrf_token %}
                    ¿Estás seguro de eliminar "{{ object }}" ?
                    <input class='btn btn-danger' type="submit" value="Borrar" />
                </form>
            {% else %}
                <p>Lo sentimos, no dispones de permisos para eliminar este item.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

gastos/templates/crud/gasto/gasto_create_form.html
{% extends 'base.html' %}
{% block extraScripts %}
{% endblock %}
{% block content %}


<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-sm-12 col-md-6">
            {% if existenCategorias %}
                {% if isOwner %}
                <h1 class="text-center">Crear gasto</h1>
                <form method="post">{% csrf_token %}
                    <p>
                        <label for="categoria">Categoría:</label>
                        <select id="categoria" name="categoria" class="form-control">
                        {% for categoria in categorias %}
                            <option value="{{categoria.id}}">{{categoria.nombre}}</option>
                        {% endfor %}
                        </select>
                    </p>
                    
                    {{ form.as_p }}
                    <input class="btn btn-primary mt-2" type="submit" value="Enviar" />
                </form>
                {% else %}
                    <p>Lo sentimos, no dispones de permisos para crear gastos en este perfil.</p>
                {% endif %}
            {% else %}
                <p class="mt-5">Para crear un gasto, antes debes crear almenos una <a href="{% url 'categoria_new' %}">categoría</a> para poder clasificarlo.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

gastos/templates/crud/gasto/gasto_form.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col">
            {% if perms.mainGastos.change_gastos and isOwner %}
            <h1>Editar gasto</h1>
            <form method="post">{% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" value="Enviar" />
            </form>
            {% else %}
                <p>Lo sentimos, no dispones de permisos para editar este item.</p>
            {% endif %}

        </div>
    </div>
</div>

{% endblock %}

gastos/templates/crud/gasto/listar_gasto.html
{% extends 'base.html' %}

{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% load static %}

{% block extraScripts %}
    <script src='{% static "styleCRUD.js" %}'></script>
    {% if perms.mainGastos.change_gastos %}
        <script src='{% static "gastosCRUD.js" %}'></script>
    {% endif %}
{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <!--
            {% if filter %}
            <form action="" method="get" class="form form-inline pt-2">
                {% bootstrap_form filter.form layout='inline' %}
                {% bootstrap_button 'filtrar' %}
            </form>
            {% endif %}
            -->
            <h1 class="text-center">Gastos - {{ nombre_perfil }} </h1>

            {% if mensajeNoGastos %}
                <p>Aún no se han añadido gastos. Puedes añadir uno nuevo <a href="{% url 'gasto_new' perfilN %}">aquí</a></p>
            {% else %}
                {% render_table table %}
                <a style='margin-bottom:50px;' class='btn btn-primary' href='{% url "gasto_new" perfilN %}'>Nuevo</a>
            {% endif %}
            
            

        </div>
    </div>
</div>

{% endblock %}